### PR TITLE
Update configure-an-sap-fiori-for-the-abap-platform-job-4c26bfb.md

### PR DESCRIPTION
**Pull request by longieirl**
Remove trailing dot, not required and causes issues when pasted into an IDE.

### CODE REVIEW

**Comment by longieirl** [comment]
@kaylinche @o-liver please review and merge if appropiate.

**Comment by kaylinche** [comment]
@SarahLendle Changes looks fine from my point of view. Can you please check?

**Review by o-liver — APPROVED** [review]

**Comment by longieirl** [comment]
@SarahLendle are you to review and merge please? Thanks

**Comment by SarahLendle** [comment]
Hi @longieirl! Thanks a lot for your contribution and sorry for the delay due to illness.

I've updated the documentation accordingly: https://help.sap.com/docs/continuous-integration-and-delivery/sap-continuous-integration-and-delivery/configure-sap-fiori-for-abap-platform-job-in-job-editor?version=Cloud

**Review by SarahLendle — APPROVED** [review]

**Pull request merged**
